### ISSUE TITLE
Expected behavior when port is defined as part of a range

### ISSUE THREAD

**Issue by mihasya** [sous-chefs/selinux_policy#53]
We are experiencing the following issue: when trying to define port 40933 as a `syslog_port_t`, the cookbook fails because it tries to call `semanage -m` (`action :modify`) on a port that is only defined as part of a range. e.g:

```
Recipe: core::configure-papertrail
* selinux_policy_port[selinux_papertrail_port] action addormodify
* execute[selinux-port-40933-add] action run (skipped due to not_if)
(up to date)
* execute[selinux-port-40933-modify] action run
================================================================================
Error executing action `run` on resource 'execute[selinux-port-40933-modify]'
================================================================================
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /usr/sbin/semanage port -m -t syslogd_port_t -p tcp 40933 ----
STDOUT:
STDERR: ValueError: Port @tcp/40933 is not defined
---- End output of /usr/sbin/semanage port -m -t syslogd_port_t -p tcp 40933 ----
Ran /usr/sbin/semanage port -m -t syslogd_port_t -p tcp 40933 returned 1
Cookbook Trace:
---------------
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
/var/chef/cookbooks/selinux_policy/providers/port.rb:57:in `block in class_from_file'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
Resource Declaration:
---------------------
# In /var/chef/cookbooks/selinux_policy/providers/port.rb
45:   execute "selinux-port-#{new_resource.port}-modify" do
46:     command "/usr/sbin/semanage port -m -t #{new_resource.secontext} -p #{new_resource.protocol} #{new_resource.port}"
47:     only_if port_defined(new_resource.protocol, new_resource.port)
48:     not_if port_defined(new_resource.protocol, new_resource.port, new_resource.secontext)
49:     only_if { use_selinux }
50:   end
51: end
```

The problem appears to be due to the fact that the `run_action(:add)` block exits due to its `not_if` clause (because the port DOES show up in the `port_defined` grep), but `run_action(:modify)` DOES execute because it's not actually defined for the appropriate context (`syslogd_port_t` in this case). So `semanage -m` is executed, but fails because it apparently doesn't recognize the port as being actually defined because it's only part of a range:

```
$ seinfo --protocol=tcp --portcon=40399
	portcon tcp 32768-61000 system_u:object_r:ephemeral_port_t:s0
```

If I manually define the port with the exact same description, it works like a charm:

```
$ /usr/sbin/semanage port -a -t ephemeral_port_t -p tcp 40933
$ seinfo --protocol=tcp --portcon=40933
	portcon tcp 40933 system_u:object_r:ephemeral_port_t:s0
	portcon tcp 32768-61000 system_u:object_r:ephemeral_port_t:s0
<rerun chef>
...
Recipe: core::configure-papertrail
  * selinux_policy_port[selinux_papertrail_port] action addormodify
    * execute[selinux-port-40933-add] action run (skipped due to not_if)
     (up to date)
  * execute[selinux-port-40933-modify] action run
    - execute /usr/sbin/semanage port -m -t syslogd_port_t -p tcp 40933
...
```

I see there's some tests in the cookbook that have to do with port ranges, but they appear incomplete. The `selinux_policy_test::range_port` cookbook appears to imply that the cookbook should fail if a port is actually modified based on a range. But that would never happen anyway, as the `-m` fails before that.

What is the actual expected behavior in this case? The following patch fixes the issue for _our_ use, in that on first run the `:add` action is triggered to explicitly define the port on its own and subsequent "do the right thing" in terms of `not_if` skipping the resources correctly. All it's doing is `grep`-ing out port ranges from `seinfo` output. I am happy to make a PR if that is the expected behavior.

```diff
diff --git a/providers/port.rb b/providers/port.rb
index 1d5139d..eb06a1b 100644
--- a/providers/port.rb
+++ b/providers/port.rb
@@ -6,7 +6,10 @@ def whyrun_supported?
 end

 def port_defined(protocol, port, label = nil)
-  base_command = "seinfo --protocol=#{protocol} --portcon=#{port} | awk -F: '$(NF-1) !~ /reserved_port_t$/ {print $(NF-1)}'"
+  # list all matches to this protocol definition, but exclude ones where it is
+  # part of a range calling semanage -m on a port that is only defined as part
+  # of a range causes it to fail
+  base_command = "seinfo --protocol=#{protocol} --portcon=#{port} | grep -vP '[\d+]-[\d+]' | awk -F: '$(NF-1) !~ /reserved_port_t$/ {print $(NF-1)}'"
   grep = if label
            "grep -P '#{Regexp.escape(label)}'"
          else
```

**Comment by BackSlasher** [comment]
This is a good question, but I think the answer varies by person.
I ignored this intentionally when I was working on the port resource because I didn't want the cookbook to do anything surprising - its behavior should be very obvious, and doing anything like modifying a range, adding a competing rule etc is not obvious.
What is your opinion on what should happen? As far as I get from a quick reading, I think you would like a new rule added. Won't that cause duplication?

**Comment by mihasya** [comment]
Re: duplication: I don't believe so, because the port is defined as an `ephemeral_port_t`, which appears to be some sort of catch-all selinux context, not the context I'm trying to add it to. I'm honestly not the strongest selinux user, so I'm not sure if having the port in both contexts would be considered problematic. But the result of this patch appears correct to me - the port is properly specified as a `syslog_port_t` and all the checks and `-a` vs `-m` distinctions work correctly.

Personally, I believe this to be a bug in `semanage`, but that feels basically insurmountable to fix on any timeline that would work. If ports can be defined in ranges, then a port that's part of a defined range should be "modifiable." It also LETS you add it explicitly, so it doesn't seem conflicted about it. Once you define it explicitly, it's happy. I haven't dug that deep yet, but I would be that `semanage` and `seinfo` use a different code path for finding out if a port is defined, and there's no obvious option for making them not do so.

**Comment by BackSlasher** [comment]
From quick googling:
https://wiki.gentoo.org/wiki/SELinux/Labels#Modifying_port_labels
Not sure I want to put this logic into the cookbook. Maybe `force` or testing.
Will sleep on it.

**Comment by mihasya** [comment]
Yup, we'll roll forward with a fork via Berksfile for now, but of course would love to get a long-term fix one way or another. Thanks!

**Comment by BackSlasher** [comment]
I don't do a lot of SELinux these days. If you could do some research about how `seinfo` and `semanage` behave with these existing port types, maybe we can come up with a behavior to handle that

**Comment by mihasya** [comment]
`ephemeral_port_t` is (apparently) equivalent to `unreserved_port_t`. If you mentally make that substitution when reading the link you posted, it sounds like my proposed logic is totally kosher. The check might need to be tightened up to specifically exclude "ephemeral" and "unreserved" labels from the "is this port defined?" check.

**Comment by BackSlasher** [comment]
So just ignore 3 specific labels when doing the `semanage` check? This sounds like it can fly. Wanna write a PR for that?

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
