### ISSUE TITLE
ArgumentError with version 2.2.0

### ISSUE THREAD

**Issue by tnguyen14** [sous-chefs/selinux_policy#90]
With the latest 2.2.0 release, this error comes up:

```
      ================================================================================
      Error executing action `create` on resource 'directory[/var/chef/cache/dockersock]'
      ================================================================================

      ArgumentError
      -------------
      wrong number of arguments (given 0, expected 1)

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/selinux_policy/libraries/helpers.rb:8:in `use_selinux'
      /var/chef/cache/cookbooks/selinux_policy/resources/module.rb:22:in `block (3 levels) in class_from_file'
      /var/chef/cache/cookbooks/selinux_policy/resources/module.rb:14:in `block in class_from_file'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/selinux_policy/resources/module.rb

       21:   directory new_resource.directory do
       22:     only_if { use_selinux }
       23:   end
       24:

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/selinux_policy/resources/module.rb:21:in `block in class_from_file'

      directory("/var/chef/cache/dockersock") do
        action [:create]
        default_guard_interpreter :default
        declared_type :directory
        cookbook_name "dltools"
        path "/var/chef/cache/dockersock"
        owner nil
        group nil
        mode nil
        only_if { #code block }
      end
```

**Comment by damacus** [comment]
Hey. Thanks for the bug report.

Would you mind making a PR to fix this up? 

I don't have enough bandwidth right now

**Comment by sspans** [comment]
Pull #92 should be good to go now, passes all tests.
