### ISSUE TITLE
RHEL 8 support?

### ISSUE THREAD

**Issue by Poohblah** [sous-chefs/selinux_policy#95]
Looks like this cookbook doesn't support RHEL 8:

```
         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/cub_policy_common/recipes/default.rb
         ================================================================================
         
         RuntimeError
         ------------
         Unknown version of RHEL/derivative, cannot determine required package names
         
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/selinux_policy/recipes/install.rb:13:in `from_file'
           /tmp/kitchen/cache/cookbooks/cub_selinux/recipes/default.rb:7:in `from_file'
           /tmp/kitchen/cache/cookbooks/cub_monitoring/recipes/nrpe.rb:16:in `from_file'
           /tmp/kitchen/cache/cookbooks/cub_monitoring/recipes/nrpe_checks.rb:10:in `from_file'
           /tmp/kitchen/cache/cookbooks/cub_monitoring/recipes/default.rb:16:in `from_file'
           /tmp/kitchen/cache/cookbooks/cub_policy_common/recipes/default.rb:8:in `block in from_file'
           /tmp/kitchen/cache/cookbooks/cub_policy_common/recipes/default.rb:7:in `each'
           /tmp/kitchen/cache/cookbooks/cub_policy_common/recipes/default.rb:7:in `from_file'
         
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/selinux_policy/recipes/install.rb:
         
           6:    case node['platform_version'].to_i
           7:    when 6
           8:      # selinux-policy-devel does not exist in RHEL6
           9:      pkgs = ['policycoreutils-python', 'selinux-policy', 'setools-console', 'make']
          10:    when 7
          11:      pkgs = ['policycoreutils-python', 'selinux-policy-devel', 'setools-console', 'make']
          12:    else
          13>>     raise 'Unknown version of RHEL/derivative, cannot determine required package names'
          14:    end
          15:  when 'fedora'
          16:    pkgs = ['policycoreutils-python', 'selinux-policy-devel', 'setools-console', 'make']
          17:  else
          18:    raise 'Unknown distro, cannot determine required package names'
          19:  end
          20:  
          21:  pkgs.each { |p| package p }
          22:  
         
         System Info:
         ------------
         chef_version=14.2.0
         platform=redhat
         platform_version=8.0
         ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
         program_name=/opt/chef/bin/chef-client
         executable=/opt/chef/bin/chef-client
```

It appears to me that the correct package names for RHEL 8 are:

```
pkgs = ['policycoreutils-python-utils', 'selinux-policy-devel', 'setools-console', 'make']
```

**Comment by damacus** [comment]
Honestly I"m not surprised due to RHEL-8 only being released into beta a week ago. 

If you are up for it, feel  free to drop us a PR with some tests!

**Comment by damacus** [comment]
Honestly that case statement is pretty harsh. If you want to look at fixing this issue, I'd start that.

**Comment by sspans** [comment]
Afaik this is fixed in 2.2.0+

**Comment by damacus** [comment]
Closing as fixed! :) Thanks for the update @sspans

**Comment by Poohblah** [comment]
Looks good to me on 2.3.0.  Thanks all
